{% set name = "daiquiri" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6252f83db9d29f1826208369c047e90e51ccbd4ee5150b5c12c16e9d8412d175

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python
    - python-json-logger

test:
  imports:
    - daiquiri
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jd/daiquiri
  summary: Library to configure Python logging easily
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
